### ISSUE TITLE
Incorrect ref passed to request?

### ISSUE THREAD

**Issue by simonihmig** [avakar/create-deployment#3]
I had an issue when this action triggered another workflow, then I got a `No scopes with read permission were found on the request.` error when installing npm dependencies using `@actions/cache`. It seems to be caused by the workflow running in a wrong context, so I fiddled around and got it fixed by adding this to the `create-deployment` setup:

```yaml
with:
  ref: ${{ github.ref }}
```

Looking at https://github.com/avakar/create-deployment/blob/master/index.js#L5, I wonder if this shouldn't rather be `const ref = core.getInput('ref') || context.ref;`?

**Comment by avakar** [comment]
You've got it, thanks for the report!
